"""DOM + computed-style snapshot test for the Svelte report SPA (RFC-001, guardrail step 1).

This is "the only oracle this migration has" (RFC-001, migration step 1): there is no visual
regression testing today, so this test serves a committed, realistic ``report.json`` fixture through
the real FastAPI app, drives the built SPA with a real Chromium via Playwright, and for each of the
six report category tabs at two viewports asserts (a) every element's tag + sorted class list with
Svelte scope-hash tokens stripped, (b) ``getComputedStyle()`` for a fixed property set on every
element whose class matches a broad "interesting" prefix list, and (c) the full set of distinct class
names present in the DOM -- the only way to catch a JS string-builder emitting a class no source grep
would find (RFC-001, "A grep-based gate cannot see interpolated class emitters").

Two viewports, not one
-----------------------
>=861px (``DESKTOP_WIDTH``) and <=860px (``MOBILE_WIDTH``). RFC-001 documents a real, currently-dead
mobile override (``report.css:951-955`` / ``:404-408`` -- a ``.form-mover`` / ``.peer-driver`` mobile
rule beaten by a same-specificity scoped Svelte rule emitted later) that a single-viewport snapshot
cannot see. A change that raises a selector's specificity (e.g. un-globalling in migration step 21)
flips who wins a tie *only* at the viewport where the loser used to matter, so both viewports must be
captured every run.

Playwright dependency decision
-------------------------------
``playwright==1.47.0`` is pinned in ``pyproject.toml``'s ``dev`` dependency group (not a base runtime
dependency -- nothing in ``src/league_stats`` imports it). Pinning the pip package pins the Chromium
build it downloads (``playwright install chromium`` resolves against the installed package version),
which is the "pinned browser version" flakiness control RFC-001 asks for; floating the dependency
would silently float the browser build too. Docs "environment without Playwright" note: a
separately-provided interpreter (as used ad hoc elsewhere for manual testing) was considered and
rejected here, because this test needs to import ``playwright.sync_api`` from the *same* interpreter
that already has FastAPI/uvicorn importable to boot the app in-process -- a separate venv would need
its own copy of this whole package. Instead the test degrades gracefully (see below) in any
environment lacking the dependency or the browser binary, so a plain ``uv sync`` without
``playwright install chromium`` does not break the suite.

Graceful degradation
---------------------
``pytest.importorskip`` gates the whole module on ``playwright.sync_api`` being importable, and the
browser fixture additionally skips if launching Chromium fails (binary not installed via
``playwright install``). This matches RFC-001's characterization of this test as "required but
rerunnable": the *dedicated* CI job that runs it builds the SPA and installs Chromium first, so the
skip never fires there and the job is a required, blocking check. In the *general* ``pytest`` run
(this repo's default job, and a contributor's local ``pytest`` invocation) neither of those steps has
necessarily happened, so hard-failing here would make an unrelated Python change fail CI/local runs
for a missing frontend toolchain -- exactly the failure mode ``test_bundle_contract.py`` avoids with
its own ``skipif spa_dist absent``. The same trade-off applies one step earlier here too: this test
additionally skips if ``spa_dist`` (the built SPA, ``npm run build`` output) is absent, for the same
reason -- "required" describes the dedicated job's gate, not a hard requirement on every pytest
invocation everywhere.

Fixture recipe
--------------
``tests/frontend/fixtures/report.json`` and ``meta.json`` were generated once, committed, and are not
regenerated by this test. Recipe (see ``tests/test_reports.py`` for the helpers):

    from tests.test_reports import _make_records, _peer, _config
    from league_stats_runner.pipeline.orchestrator import run_analysis
    from league_stats_common.core.models import RankedEntry
    from league_stats_common.infra.ddragon_assets import DDragonAssets

    DDragonAssets.ensure_downloaded = lambda self, force=False: ""
    DDragonAssets.ensure_champion_ability_icons = lambda self, champion: None

    records = _make_records(40)  # 40 games -> every report section has real data, no
                                  # "insufficient data" placeholders
    peer = _peer(records)        # peer comparison populated
    ranked = RankedEntry(tier="GOLD", rank="II", league_points=45, wins=80, losses=75)
    config = _config(tmp_path, champion="Viktor", role="MIDDLE")
    run_analysis(config, records, peer_comparison=peer, ranked=ranked)
    # -> tmp_path/output/reports/test_euw/viktor_middle/{meta.json,report.json}

Serving it
----------
A real ``uvicorn`` server (not ``TestClient`` -- Playwright drives a real browser over real HTTP) is
started in a background thread on a dynamically-allocated free port (not a hardcoded fixed port,
despite the task brief's example: this suite runs under ``pytest-xdist -n auto``, so a fixed port
would collide across parallel workers). The fixture report/meta pair is copied into a temp
``WebConfig.output_dir`` before the app starts, exactly mirroring ``tests/test_web_api.py``'s
``_write_report`` shape.

Animation-disable and render-complete wait
-------------------------------------------
An init script (``BrowserContext.add_init_script``) injects a ``<style>`` forcing
``animation: none !important; transition: none !important`` onto ``document.documentElement`` as
early as the DOM allows, before the SPA's own module script runs. This is explicitly *not*
``wait_for_timeout`` (RFC-001 calls out ``deploy/compare_design.py``'s old 600/1500/6000ms constants
as the anti-pattern to avoid, and that file is deleted on the target branch). Render completion is
instead a concrete DOM signal: the loading state (``.report-loading``) is replaced by
``#report-category-tabs`` once ``fetchBuild`` resolves and Svelte renders the real content, and
switching tabs is awaited by polling for ``.report-category-panel.is-active[data-category=...]``
existing. Server-startup readiness (waiting for ``/health`` to answer before Playwright connects) is a
separate, bounded poll loop -- an infra bring-up wait, not a page-render wait, so it is not what the
RFC's warning is about.

Baselines
---------
One JSON file per (tab, viewport) under ``tests/frontend/snapshots/`` -- 12 files. Missing baselines
are written on the spot (bootstrap / first run); set ``UPDATE_SNAPSHOTS=1`` to force a rewrite on a
run where the tree is known-good. Otherwise a mismatch fails with the exact selector identity
(``tag.class1.class2 (#N)``, N being the Nth element in document order with that exact tag+class
combination) and property that changed.

Scope note for whoever integrates this after RFC-001's component-migration steps land: these
baselines were captured against *this* worktree's pre-migration ``main`` (commit ``683033f``), not
against any in-flight component rewrite happening in parallel elsewhere. They will need a full
regeneration pass (delete ``tests/frontend/snapshots/*.json``, rerun with ``UPDATE_SNAPSHOTS=1``) once
everything merges -- that is expected, not a bug in this harness.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import socket
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Iterator

import pytest

playwright_sync_api = pytest.importorskip("playwright.sync_api")

from league_stats_common.core.config import WebConfig  # noqa: E402
from league_stats_api_ui.app import create_app  # noqa: E402

FRONTEND_TESTS_DIR = Path(__file__).resolve().parent
FIXTURES_DIR = FRONTEND_TESTS_DIR / "fixtures"
SNAPSHOTS_DIR = FRONTEND_TESTS_DIR / "snapshots"
SPA_DIST_DIR = Path(__file__).resolve().parent.parent.parent / "src/league_stats_api_ui/spa_dist"

REPORT_SLUG = "test_euw"
BUILD_SLUG = "viktor_middle"

TABS = ["summary", "games", "career", "performance", "champion", "deepdive"]

DESKTOP_VIEWPORT = {"width": 1440, "height": 900}
MOBILE_VIEWPORT = {"width": 390, "height": 844}
VIEWPORTS_BY_NAME = {"desktop": DESKTOP_VIEWPORT, "mobile": MOBILE_VIEWPORT}

# Broad, intentionally over-inclusive prefix list: any class *starting with* one of these is a
# "watched" element whose computed style gets captured. This is not meant to be exhaustive or
# precisely targeted -- the point (per RFC-001) is that a family-wide rename or a specificity
# inversion should trip at least one of these prefixes without needing per-component maintenance
# every time a new chip/card/table variant is added.
WATCHED_CLASS_PREFIXES = [
    "pill",
    "chip",
    "card",
    "cards",
    "section-title",
    "sub",
    "metric",
    "game-review-",
    "gr-",
    "form-",
    "peer-",
    "meter",
    "score",
    "panel",
    "callout",
    "table",
    "sort-btn",
    "tab",
    "dossier",
    "rec-",
    "matchup-",
    "objective-",
    "hero",
    "stat-chip",
    "tone-label",
    "career",
    "skill-",
    "watch-toggle",
    "avatar",
    "account",
    "btn",
    "nav-",
    "figure",
    "positioning-",
    "teamfight-",
    "vision-",
    "death-",
    "lane-",
    "build-",
    "rune-",
    "top-tip",
    "back-to-top",
    "disclosure",
    "show-more",
]

WATCHED_PROPERTIES = [
    "color",
    "background-color",
    "border-color",
    "border-radius",
    "font-size",
    "font-weight",
    "padding",
    "gap",
    "display",
]

SVELTE_HASH_RE = re.compile(r"^svelte-[a-z0-9]+$")

_CAPTURE_JS = """
([scopeSelector, prefixes, properties]) => {
  const root = document.querySelector(scopeSelector);
  if (!root) return null;
  const svelteHashRe = /^svelte-[a-z0-9]+$/;
  const all = Array.from(root.querySelectorAll('*'));
  const occurrence = {};
  const elements = [];
  const watched = [];
  const classSet = new Set();
  for (const el of all) {
    const tag = el.tagName.toLowerCase();
    const classes = Array.from(el.classList)
      .filter((c) => !svelteHashRe.test(c))
      .sort();
    classes.forEach((c) => classSet.add(c));
    const key = tag + '.' + classes.join('.');
    occurrence[key] = (occurrence[key] || 0) + 1;
    const selector = classes.length ? `${tag}.${classes.join('.')}` : tag;
    const identity = `${selector} (#${occurrence[key]})`;
    elements.push({ identity, tag, classes });
    const isWatched = classes.some((c) => prefixes.some((p) => c.startsWith(p)));
    if (isWatched) {
      const style = window.getComputedStyle(el);
      const styles = {};
      for (const prop of properties) styles[prop] = style.getPropertyValue(prop);
      watched.push({ identity, tag, classes, styles });
    }
  }
  return { elements, watched, class_set: Array.from(classSet).sort() };
}
"""

_DISABLE_ANIMATIONS_INIT_SCRIPT = """
(() => {
  const inject = () => {
    if (!document.documentElement) {
      requestAnimationFrame(inject);
      return;
    }
    const style = document.createElement('style');
    style.id = '__pw_disable_animations__';
    style.textContent = `
      *, *::before, *::after {
        animation: none !important;
        transition: none !important;
        scroll-behavior: auto !important;
      }
    `;
    document.documentElement.appendChild(style);
  };
  inject();
})();
"""


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def _wait_for_server(base_url: str, timeout_s: float = 10.0) -> None:
    """Poll server startup readiness. Infra bring-up, not a page-render wait."""
    deadline = time.monotonic() + timeout_s
    last_error: Exception | None = None
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(f"{base_url}/health", timeout=0.5) as response:
                if response.status == 200:
                    return
        except (urllib.error.URLError, ConnectionError, OSError) as exc:
            last_error = exc
            time.sleep(0.05)
    raise RuntimeError(f"server did not become ready at {base_url}") from last_error


@pytest.fixture(scope="module")
def report_server(tmp_path_factory: pytest.TempPathFactory) -> Iterator[str]:
    if not SPA_DIST_DIR.is_dir():
        pytest.skip(
            "spa_dist absent: run `npm run build` in frontend/ first. This test's dedicated CI "
            "job does that before invoking it; it is not expected to run in a plain `pytest` "
            "invocation that has never built the SPA."
        )

    import uvicorn

    tmp_path = tmp_path_factory.mktemp("render_snapshot")
    report_dir = tmp_path / "output" / "reports" / REPORT_SLUG / BUILD_SLUG
    report_dir.mkdir(parents=True)
    shutil.copy(FIXTURES_DIR / "report.json", report_dir / "report.json")
    shutil.copy(FIXTURES_DIR / "meta.json", report_dir / "meta.json")

    config = WebConfig(
        app_db_path=tmp_path / "app.sqlite",
        output_dir=tmp_path / "output",
        gemini_api_key="fake-key",
        port=_free_port(),
        runner_storage_mode="sqlite",
    )
    application = create_app(config, start_worker=False)

    server_config = uvicorn.Config(
        application, host="127.0.0.1", port=config.port, log_level="warning"
    )
    server = uvicorn.Server(server_config)
    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()

    base_url = f"http://127.0.0.1:{config.port}"
    try:
        _wait_for_server(base_url)
        yield base_url
    finally:
        server.should_exit = True
        thread.join(timeout=5)


@pytest.fixture(scope="module")
def browser() -> Iterator[Any]:
    from playwright.sync_api import sync_playwright

    with sync_playwright() as playwright:
        try:
            chromium = playwright.chromium.launch()
        except Exception as exc:  # noqa: BLE001 - browser binary missing/unlaunchable
            pytest.skip(f"Chromium unavailable for Playwright ({exc}); run `playwright install "
                        "chromium`.")
            return
        try:
            yield chromium
        finally:
            chromium.close()


@pytest.fixture()
def viewport_name(request: pytest.FixtureRequest) -> str:
    """Indirect fixture: receives the parametrized viewport name via `request.param`."""
    return request.param


def _block_third_party_cdns(route: Any) -> None:
    """Abort requests to the two CDNs `index.html` hardcodes (Plotly, Iconify).

    Both render asynchronously after the page's own render-complete signal fires (Plotly builds
    real SVG chart DOM well after ``fetchBuild`` resolves), so leaving them reachable makes the
    snapshot's element count and structure a function of network timing -- exactly the kind of
    flakiness this test must not have. `PlotlyFigure.svelte` sets the container's `innerHTML`
    directly from the payload (see its module docstring), so the structural DOM (a wrapper div
    plus an empty `.plotly-graph-div`) is fully deterministic without the library ever loading;
    only pixel-level chart rendering is lost, which this test never asserts on anyway.
    """
    route.abort()


@pytest.fixture()
def report_page(browser: Any, report_server: str, viewport_name: str) -> Iterator[Any]:
    context = browser.new_context(viewport=VIEWPORTS_BY_NAME[viewport_name])
    context.add_init_script(_DISABLE_ANIMATIONS_INIT_SCRIPT)
    context.route("https://cdn.plot.ly/**", _block_third_party_cdns)
    context.route("https://code.iconify.design/**", _block_third_party_cdns)
    context.route("https://fonts.googleapis.com/**", _block_third_party_cdns)
    context.route("https://fonts.gstatic.com/**", _block_third_party_cdns)
    page = context.new_page()
    page.goto(f"{report_server}/#/players/{REPORT_SLUG}/{BUILD_SLUG}")
    page.wait_for_selector("#report-category-tabs", state="attached", timeout=15000)
    try:
        yield page
    finally:
        context.close()


def _select_tab(page: Any, tab: str) -> None:
    if tab != "summary":
        page.click(f'#report-category-tabs button[data-category="{tab}"]')
    page.wait_for_selector(
        f'.report-category-panel.is-active[data-category="{tab}"]', state="attached", timeout=15000
    )


def _capture(page: Any, tab: str) -> dict[str, Any]:
    scope_selector = f'.report-category-panel[data-category="{tab}"]'
    result = page.evaluate(_CAPTURE_JS, [scope_selector, WATCHED_CLASS_PREFIXES, WATCHED_PROPERTIES])
    assert result is not None, f"panel for tab {tab!r} not found in the DOM"
    return result


def _baseline_path(tab: str, viewport_name: str) -> Path:
    return SNAPSHOTS_DIR / f"{tab}_{viewport_name}.json"


def _diff_snapshots(baseline: dict[str, Any], current: dict[str, Any]) -> list[str]:
    diffs: list[str] = []

    base_elements = baseline.get("elements", [])
    cur_elements = current.get("elements", [])
    if len(base_elements) != len(cur_elements):
        diffs.append(
            f"element count changed: baseline had {len(base_elements)}, now {len(cur_elements)}"
        )
    for index, (base_el, cur_el) in enumerate(zip(base_elements, cur_elements)):
        if base_el["tag"] != cur_el["tag"] or base_el["classes"] != cur_el["classes"]:
            diffs.append(
                f"element #{index} changed: {base_el['tag']}.{'.'.join(base_el['classes'])} "
                f"-> {cur_el['tag']}.{'.'.join(cur_el['classes'])}"
            )

    base_classes = set(baseline.get("class_set", []))
    cur_classes = set(current.get("class_set", []))
    added = sorted(cur_classes - base_classes)
    removed = sorted(base_classes - cur_classes)
    if added:
        diffs.append(f"new class names present in the DOM (no source grep would catch these): {added}")
    if removed:
        diffs.append(f"class names no longer present in the DOM: {removed}")

    base_watched = {entry["identity"]: entry for entry in baseline.get("watched", [])}
    cur_watched = {entry["identity"]: entry for entry in current.get("watched", [])}
    for identity in sorted(set(base_watched) - set(cur_watched)):
        diffs.append(f"watched element disappeared: {identity}")
    for identity in sorted(set(cur_watched) - set(base_watched)):
        diffs.append(f"new watched element appeared: {identity}")
    for identity in sorted(set(base_watched) & set(cur_watched)):
        base_styles = base_watched[identity]["styles"]
        cur_styles = cur_watched[identity]["styles"]
        for prop, base_value in base_styles.items():
            cur_value = cur_styles.get(prop)
            if base_value != cur_value:
                diffs.append(f"{identity}: {prop} changed from {base_value!r} to {cur_value!r}")

    return diffs


def _assert_matches_baseline(tab: str, viewport_name: str, captured: dict[str, Any]) -> None:
    SNAPSHOTS_DIR.mkdir(parents=True, exist_ok=True)
    path = _baseline_path(tab, viewport_name)
    update = os.environ.get("UPDATE_SNAPSHOTS") == "1"

    if update or not path.is_file():
        path.write_text(json.dumps(captured, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        return

    baseline = json.loads(path.read_text(encoding="utf-8"))
    diffs = _diff_snapshots(baseline, captured)
    if diffs:
        message = "\n".join(
            [f"render snapshot mismatch for tab={tab!r} viewport={viewport_name!r}:"]
            + [f"  - {line}" for line in diffs]
            + ["", f"If this is an intentional change, rerun with UPDATE_SNAPSHOTS=1 to accept it."]
        )
        pytest.fail(message)


@pytest.mark.parametrize("tab", TABS)
@pytest.mark.parametrize("viewport_name", list(VIEWPORTS_BY_NAME), indirect=True)
def test_render_snapshot(report_page: Any, tab: str, viewport_name: str) -> None:
    """Snapshot one report category tab at one viewport against its committed baseline."""
    _select_tab(report_page, tab)
    captured = _capture(report_page, tab)
    _assert_matches_baseline(tab, viewport_name, captured)


# --------------------------------------------------------------------------------
# Deep-linkable tabs: the report category is part of the URL (`.../:tab?` in
# App.svelte), so a bookmark taken from any tab reopens on that tab. These reuse
# the module's server/browser fixtures directly rather than the viewport-
# parametrized `report_page` one above, since they test navigation, not rendering.
# --------------------------------------------------------------------------------


def test_direct_navigation_to_a_tab_url_opens_that_tab(browser: Any, report_server: str) -> None:
    """The entire point of the feature: opening a bookmarked tab URL fresh must show
    that tab immediately, with no click through the tab bar needed."""
    context = browser.new_context(viewport=DESKTOP_VIEWPORT)
    page = context.new_page()
    try:
        page.goto(f"{report_server}/#/players/{REPORT_SLUG}/{BUILD_SLUG}/career")
        page.wait_for_selector(
            '.report-category-panel.is-active[data-category="career"]',
            state="attached",
            timeout=15000,
        )
        summary_panel = page.query_selector('.report-category-panel[data-category="summary"]')
        assert summary_panel is not None
        assert "is-active" not in (summary_panel.get_attribute("class") or "")
    finally:
        context.close()


def test_clicking_a_tab_updates_the_url_so_it_can_be_bookmarked(
    browser: Any, report_server: str
) -> None:
    """A tab switch must rewrite the address bar, or a bookmark taken right after
    clicking a tab would silently reopen on summary instead."""
    context = browser.new_context(viewport=DESKTOP_VIEWPORT)
    page = context.new_page()
    try:
        page.goto(f"{report_server}/#/players/{REPORT_SLUG}/{BUILD_SLUG}")
        page.wait_for_selector("#report-category-tabs", state="attached", timeout=15000)
        page.click('#report-category-tabs button[data-category="career"]')
        page.wait_for_selector(
            '.report-category-panel.is-active[data-category="career"]',
            state="attached",
            timeout=15000,
        )
        assert page.evaluate("window.location.hash") == (
            f"#/players/{REPORT_SLUG}/{BUILD_SLUG}/career"
        )
    finally:
        context.close()


def test_a_tab_switch_does_not_add_a_history_entry(browser: Any, report_server: str) -> None:
    """Tab switches use replace(), not push(): the back button should leave the
    report, not step back through the tabs the user happened to click through."""
    context = browser.new_context(viewport=DESKTOP_VIEWPORT)
    page = context.new_page()
    try:
        # Two real navigations bracket the tab clicks, so "back" has something real
        # to land on -- a fresh page's history has nothing before its first goto().
        page.goto(f"{report_server}/")
        page.goto(f"{report_server}/#/players/{REPORT_SLUG}/{BUILD_SLUG}")
        page.wait_for_selector("#report-category-tabs", state="attached", timeout=15000)
        for tab in ("career", "games", "champion"):
            page.click(f'#report-category-tabs button[data-category="{tab}"]')
            page.wait_for_selector(
                f'.report-category-panel.is-active[data-category="{tab}"]',
                state="attached",
                timeout=15000,
            )
        page.go_back()
        page.wait_for_timeout(200)
        # Three replace()s collapsed into the report's one history entry: back from
        # "champion" must land on the pre-report page, not on "games" or "career".
        assert page.evaluate("window.location.hash") in ("", "#/")
    finally:
        context.close()


def test_an_unknown_tab_segment_falls_back_to_summary(browser: Any, report_server: str) -> None:
    """A stale or hand-edited tab segment must render the report, not a blank page."""
    context = browser.new_context(viewport=DESKTOP_VIEWPORT)
    page = context.new_page()
    try:
        page.goto(f"{report_server}/#/players/{REPORT_SLUG}/{BUILD_SLUG}/not-a-real-tab")
        page.wait_for_selector(
            '.report-category-panel.is-active[data-category="summary"]',
            state="attached",
            timeout=15000,
        )
    finally:
        context.close()
