"""Career ladder orchestration: seed, advance, retire, shift, regenerate.

Runs once per report build. Only the leftmost block is measured; when all three
of its goals count, it retires, the queued block shifts left, and a fresh one is
generated by re-ranking the track pool against the build's *current* category
weaknesses -- never against an order decided when the ladder started.

The ladder always shows ``BLOCK_SLOTS`` blocks. Which tracks fill them is driven
by the coach's significance signals, but a track that is not currently flagged is
still offered as a stretch goal rather than leaving a slot empty. The queue is
kept deliberately short so a newly generated block reflects what the player is
actually weakest at right now.

All three goals in the live block are measured at once, not unlocked one after
another: three sequential 20-game windows would take 60 games to clear a block.
Each block also records the timestamp it was generated at, so it only ever
counts games played *after* it appeared -- otherwise a block would inherit
credit from games that were already in the bag and could complete the moment it
was created.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from league_stats.analysis.career.models import (
    BLOCK_SLOTS,
    StoredGoal,
    WINDOW,
)
from league_stats.analysis.career.state import block_is_complete, transition
from league_stats.analysis.career.tracks import (
    TRACKS_BY_KEY,
    TrackContext,
    build_rungs,
    rank_track_keys,
    track_spec,
)
from league_stats.analysis.career.window import count_hits, newest_game_ms, recent_window
from league_stats.infra.career_store import CareerStore
from league_stats.utils import get_logger

from typing import Any, Sequence


@dataclass(frozen=True)
class CareerBlockState:
    """One ladder slot: its track and its goals, with this window's hit counts."""

    slot: int
    track_key: str
    goals: list[StoredGoal]
    hits: list[int] = field(default_factory=list)
    display_states: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class CareerSnapshot:
    """The ladder as it stands after this run."""

    blocks: list[CareerBlockState] = field(default_factory=list)
    pending_congrats: str = ""
    window: int = WINDOW
    awaiting_peers: bool = False


def advance_career(
    store: CareerStore,
    key: str,
    ctx: TrackContext,
    components: Sequence[Any],
) -> CareerSnapshot:
    """Seed or advance a ladder and return its post-run state."""
    log = get_logger("career")

    requested = store.peek_pending_drop(key)
    if requested is not None:
        store.clear_pending_drop(key)
        if store.load_goals(key):
            return drop_block(store, key, requested, ctx, components)

    _drop_provisional_blocks(store, key, ctx)
    requested = store.peek_pending_drop(key)
    if requested is not None:
        store.clear_pending_drop(key)
        if store.load_goals(key):
            return drop_block(store, key, requested, ctx, components)

    _drop_orphaned_blocks(store, key)
    _drop_provisional_blocks(store, key, ctx)
    _fill_empty_slots(store, key, ctx, components)
    if not store.load_goals(key):
        if not ctx.can_seed_blocks():
            log.info("Career ladder waiting for peer comparison for %s", key)
            return CareerSnapshot(awaiting_peers=True)
        log.info("No eligible Career tracks for %s yet", key)
        return CareerSnapshot()

    _measure_live_block(store, key, ctx)

    live = _slot_goals(store, key, 0)
    if live and block_is_complete([goal.state for goal in live]):
        retired = live[0].track_key
        _retire_live_block(store, key, ctx, components, retired)
        log.info("Career block %s retired for %s", retired, key)
        _measure_live_block(store, key, ctx)

    return _snapshot(store, key, ctx)


def drop_block(
    store: CareerStore,
    key: str,
    slot: int,
    ctx: TrackContext,
    components: Sequence[Any],
) -> CareerSnapshot:
    """Discard one block by hand, shift the queue left and generate a replacement.

    Unlike a retire this does not record the track as used and raises no
    block-complete banner, so a dropped track stays fully eligible. If it is
    still the best fit for this build it comes straight back, with rungs
    recomputed against whatever peer data exists now.
    """
    log = get_logger("career")
    existing = _slot_goals(store, key, slot)
    if not existing:
        return _snapshot(store, key, ctx)

    dropped = existing[0].track_key
    store.delete_slot(key, slot)
    promoted_since = newest_game_ms(ctx.matches_df)
    for source in range(slot + 1, BLOCK_SLOTS):
        store.move_slot(key, source, source - 1, since_ms=promoted_since)
    _fill_empty_slots(store, key, ctx, components)
    log.info("Career block %s dropped from slot %d for %s", dropped, slot, key)

    _measure_live_block(store, key, ctx)
    return _snapshot(store, key, ctx)


def _drop_orphaned_blocks(store: CareerStore, key: str) -> None:
    """Discard blocks whose track no longer exists in the pool.

    A track removed from ``TRACK_SPECS`` between releases leaves goals on disk
    that nothing can regenerate or retarget: :func:`_rungs_for` returns None for
    it, and if its column went away with it the block can never clear either, so
    it would hold its slot forever. Dropping it frees the slot for a live track.

    It is not recorded as used -- it is not in the pool to recycle.
    """
    orphaned = sorted(
        {goal.slot for goal in store.load_goals(key) if goal.track_key not in TRACKS_BY_KEY}
    )
    if not orphaned:
        return
    log = get_logger("career")
    for slot in orphaned:
        log.info("Dropping Career slot %d for %s: track left the pool", slot, key)
        store.delete_slot(key, slot)


def _drop_provisional_blocks(store: CareerStore, key: str, ctx: TrackContext) -> None:
    """Discard blocks frozen before peer percentiles existed, if unstarted.

    Stage A of the web pipeline renders with ``peer_comparison=None``, so a
    ladder seeded then stepped toward the player's own p75 and its track order
    never saw the peer significance signals. Deleting those slots here lets
    :func:`_fill_empty_slots` rebuild them against peers on the same run.

    A block the player has already made progress on is left alone: rung targets
    must never move under someone closing in on them.
    """
    if not ctx.peer_p75:
        return
    stale = sorted(
        {
            goal.slot
            for goal in store.load_goals(key)
            if not goal.peer_seeded and not _slot_started(store, key, goal.slot, ctx)
        }
    )
    for slot in stale:
        store.delete_slot(key, slot)


def _slot_started(store: CareerStore, key: str, slot: int, ctx: TrackContext) -> bool:
    """Whether any goal in a slot has banked a game or left its opening state."""
    return any(
        goal.state != "In progress" or _goal_hits(goal, ctx) > 0
        for goal in _slot_goals(store, key, slot)
    )


def _fill_empty_slots(
    store: CareerStore,
    key: str,
    ctx: TrackContext,
    components: Sequence[Any],
) -> None:
    """Top the ladder back up to a full set of blocks.

    New blocks wait for peer percentiles. Stage A of the web pipeline renders
    with ``peer_comparison=None``; seeding then would freeze own-p75 rungs and
    a track order that never saw rank significance. Existing blocks are still
    measured so a live ladder does not stall while peers catch up.
    """
    if not ctx.can_seed_blocks():
        return
    goals = store.load_goals(key)
    taken = {goal.track_key for goal in goals}
    empty = [slot for slot in range(BLOCK_SLOTS) if not any(g.slot == slot for g in goals)]
    if not empty:
        return
    used = store.used_track_keys(key)
    since_ms = newest_game_ms(ctx.matches_df)
    for track_key in candidate_step_keys(components, ctx, taken, used):
        if not empty:
            break
        if track_key in taken:
            continue
        rungs = _rungs_for(track_key, ctx)
        if rungs is None:
            continue
        store.write_slot(
            key,
            empty.pop(0),
            track_key,
            rungs,
            ["In progress"] * len(rungs),
            since_ms=since_ms,
            peer_seeded=bool(ctx.peer_p75),
        )
        taken.add(track_key)


def candidate_step_keys(
    components: Sequence[Any],
    ctx: TrackContext,
    taken: set[str],
    used: set[str],
) -> list[str]:
    """Block keys in the order the ladder should hand them out.

    Fresh before recycled, then weakest improvement-score category first. Every
    category the role has is offered, so the ladder always fills; which *goals*
    land inside a block is decided by the step bank at build time.
    """
    ranked = rank_track_keys(components, exclude=taken, role=ctx.role)
    return sorted(ranked, key=lambda key: (key in used, ranked.index(key)))



def _rungs_for(track_key: str, ctx: TrackContext) -> tuple[Any, ...] | None:
    spec = track_spec(track_key)
    if spec is None:
        return None
    return build_rungs(spec, ctx)


def _slot_goals(store: CareerStore, key: str, slot: int) -> list[StoredGoal]:
    return [goal for goal in store.load_goals(key) if goal.slot == slot]


def _goal_hits(goal: StoredGoal, ctx: TrackContext) -> int:
    """Games meeting this goal, counted only from when its block was generated."""
    window_df = recent_window(ctx.matches_df, since_ms=goal.since_ms)
    return count_hits(window_df, goal.rung)


def _measure_live_block(store: CareerStore, key: str, ctx: TrackContext) -> None:
    """Recompute and persist every slot-0 state; later slots are not measured."""
    live = _slot_goals(store, key, 0)
    if not live:
        return
    states = {
        (goal.slot, goal.goal_index): transition(
            goal.state, _goal_hits(goal, ctx), goal.rung.need
        )
        for goal in live
    }
    store.save_goal_states(key, states)


def _retire_live_block(
    store: CareerStore,
    key: str,
    ctx: TrackContext,
    components: Sequence[Any],
    retired: str,
) -> None:
    """Drop the finished block, shift the rest left, generate a new last slot.

    Promotion re-stamps the start line so a block that has been sitting queued
    starts counting from now, not from whenever it was first generated.
    """
    store.record_used_track(key, retired)
    store.set_pending_congrats(key, retired)
    store.delete_slot(key, 0)
    promoted_since = newest_game_ms(ctx.matches_df)
    for slot in range(1, BLOCK_SLOTS):
        store.move_slot(key, slot, slot - 1, since_ms=promoted_since)
    _fill_empty_slots(store, key, ctx, components)


def _snapshot(store: CareerStore, key: str, ctx: TrackContext) -> CareerSnapshot:
    """Assemble the display view: live block measured, queued blocks inert.

    Every goal in the live block reports its own count -- there is no
    within-block lock cascade, so all three progress in parallel.
    """
    goals = store.load_goals(key)
    blocks: list[CareerBlockState] = []
    for slot in range(BLOCK_SLOTS):
        slot_goals = [goal for goal in goals if goal.slot == slot]
        if not slot_goals:
            continue
        if slot == 0:
            hits = [_goal_hits(goal, ctx) for goal in slot_goals]
            display = [goal.state for goal in slot_goals]
        else:
            hits = [0] * len(slot_goals)
            display = ["Locked"] * len(slot_goals)
        blocks.append(
            CareerBlockState(
                slot=slot,
                track_key=slot_goals[0].track_key,
                goals=slot_goals,
                hits=hits,
                display_states=display,
            )
        )
    return CareerSnapshot(
        blocks=blocks,
        pending_congrats=store.peek_pending_congrats(key),
    )
