"""Career ladder orchestration: seed, advance, retire, shift, regenerate.

Runs once per report build. Only the leftmost block is measured; when all three
of its goals count, it retires, the other two shift left, and a fresh third block
is generated by re-ranking the eligible tracks against the build's *current*
category weaknesses -- never against an order decided when the ladder started.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from league_stats.analysis.career.models import (
    BLOCK_SLOTS,
    StoredGoal,
    WINDOW,
)
from league_stats.analysis.career.state import apply_lock_overlay, block_is_complete, transition
from league_stats.analysis.career.tracks import (
    TrackContext,
    build_rungs,
    rank_track_keys,
    track_spec,
)
from league_stats.analysis.career.window import count_hits, recent_window
from league_stats.infra.career_store import CareerStore
from league_stats.utils import get_logger

from typing import Any, Sequence


@dataclass(frozen=True)
class CareerBlockState:
    """One ladder slot: its track and its goals, with this window's hit counts."""

    slot: int
    track_key: str
    goals: list[StoredGoal]
    hits: list[int] = field(default_factory=list)
    display_states: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class CareerSnapshot:
    """The ladder as it stands after this run."""

    blocks: list[CareerBlockState] = field(default_factory=list)
    pending_congrats: str = ""
    window: int = WINDOW


def advance_career(
    store: CareerStore,
    key: str,
    ctx: TrackContext,
    components: Sequence[Any],
) -> CareerSnapshot:
    """Seed or advance a ladder and return its post-run state."""
    log = get_logger("career")
    window_df = recent_window(ctx.matches_df)

    _fill_empty_slots(store, key, ctx, components)
    if not store.load_goals(key):
        log.info("No eligible Career tracks for %s yet", key)
        return CareerSnapshot()

    _measure_live_block(store, key, window_df)

    live = _slot_goals(store, key, 0)
    if live and block_is_complete([goal.state for goal in live]):
        retired = live[0].track_key
        _retire_live_block(store, key, ctx, components, retired)
        log.info("Career block %s retired for %s", retired, key)
        _measure_live_block(store, key, window_df)

    return _snapshot(store, key, window_df)


def _fill_empty_slots(
    store: CareerStore,
    key: str,
    ctx: TrackContext,
    components: Sequence[Any],
) -> None:
    """Top the ladder up to three blocks, weakest eligible category first.

    This runs every time rather than only on the first report: a build whose peer
    comparison had not landed yet, or whose pool was briefly thin, would otherwise
    stay short of three blocks forever.
    """
    goals = store.load_goals(key)
    taken = {goal.track_key for goal in goals}
    empty = [slot for slot in range(BLOCK_SLOTS) if not any(g.slot == slot for g in goals)]
    if not empty:
        return
    used = store.used_track_keys(key)
    for track_key in _candidate_order(components, taken, used):
        if not empty:
            break
        if track_key in taken:
            continue
        rungs = _rungs_for(track_key, ctx)
        if rungs is None:
            continue
        store.write_slot(key, empty.pop(0), track_key, rungs, ["In progress"] * len(rungs))
        taken.add(track_key)


def _candidate_order(
    components: Sequence[Any],
    taken: set[str],
    used: set[str],
) -> list[str]:
    """Weakest-first candidates, fresh tracks before ones already retired once."""
    ranked = rank_track_keys(components, exclude=taken)
    fresh = [key for key in ranked if key not in used]
    recycled = [key for key in ranked if key in used]
    return fresh + recycled


def _rungs_for(track_key: str, ctx: TrackContext) -> tuple[Any, ...] | None:
    spec = track_spec(track_key)
    if spec is None:
        return None
    return build_rungs(spec, ctx)


def _slot_goals(store: CareerStore, key: str, slot: int) -> list[StoredGoal]:
    return [goal for goal in store.load_goals(key) if goal.slot == slot]


def _measure_live_block(store: CareerStore, key: str, window_df: Any) -> None:
    """Recompute and persist states for slot 0; later slots are not measured."""
    live = _slot_goals(store, key, 0)
    if not live:
        return
    states = {
        (goal.slot, goal.goal_index): transition(
            goal.state, count_hits(window_df, goal.rung), goal.rung.need
        )
        for goal in live
    }
    store.save_goal_states(key, states)


def _retire_live_block(
    store: CareerStore,
    key: str,
    ctx: TrackContext,
    components: Sequence[Any],
    retired: str,
) -> None:
    """Drop the finished block, shift the rest left, generate a new last slot."""
    store.record_used_track(key, retired)
    store.set_pending_congrats(key, retired)
    store.delete_slot(key, 0)
    for slot in range(1, BLOCK_SLOTS):
        store.move_slot(key, slot, slot - 1)
    _fill_empty_slots(store, key, ctx, components)


def _snapshot(store: CareerStore, key: str, window_df: Any) -> CareerSnapshot:
    """Assemble the display view: live block measured and overlaid, rest inert."""
    goals = store.load_goals(key)
    blocks: list[CareerBlockState] = []
    for slot in range(BLOCK_SLOTS):
        slot_goals = [goal for goal in goals if goal.slot == slot]
        if not slot_goals:
            continue
        if slot == 0:
            hits = [count_hits(window_df, goal.rung) for goal in slot_goals]
            display = apply_lock_overlay([goal.state for goal in slot_goals])
        else:
            hits = [0] * len(slot_goals)
            display = ["Locked"] * len(slot_goals)
        blocks.append(
            CareerBlockState(
                slot=slot,
                track_key=slot_goals[0].track_key,
                goals=slot_goals,
                hits=hits,
                display_states=display,
            )
        )
    return CareerSnapshot(
        blocks=blocks,
        pending_congrats=store.take_pending_congrats(key),
    )
