# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: league_stats_rpc/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'league_stats_rpc/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n league_stats_rpc/v1/common.proto\x12\x13league_stats_rpc.v1\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*M\n\x06Region\x12\x16\n\x12REGION_UNSPECIFIED\x10\x00\x12\n\n\x06\x45UROPE\x10\x01\x12\x0c\n\x08\x41MERICAS\x10\x02\x12\x08\n\x04\x41SIA\x10\x03\x12\x07\n\x03SEA\x10\x04*Y\n\x05Stage\x12\x15\n\x11STAGE_UNSPECIFIED\x10\x00\x12\x0b\n\x07SUMMARY\x10\x01\x12\x0f\n\x0bPERFORMANCE\x10\x02\x12\r\n\tDEEP_DIVE\x10\x03\x12\x0c\n\x08\x43HAMPION\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'league_stats_rpc.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGION']._serialized_start=93
  _globals['_REGION']._serialized_end=170
  _globals['_STAGE']._serialized_start=172
  _globals['_STAGE']._serialized_end=261
  _globals['_ACK']._serialized_start=57
  _globals['_ACK']._serialized_end=91
# @@protoc_insertion_point(module_scope)
