# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from league_stats_rpc.v1 import common_pb2 as league__stats__rpc_dot_v1_dot_common__pb2
from league_stats_rpc.v1 import cron_watch_pb2 as league__stats__rpc_dot_v1_dot_cron__watch__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in league_stats_rpc/v1/cron_watch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CronWatchServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAccount = channel.unary_unary(
                '/league_stats_rpc.v1.CronWatchService/RegisterAccount',
                request_serializer=league__stats__rpc_dot_v1_dot_cron__watch__pb2.RegisterAccountRequest.SerializeToString,
                response_deserializer=league__stats__rpc_dot_v1_dot_common__pb2.Ack.FromString,
                _registered_method=True)
        self.ForceRefresh = channel.unary_unary(
                '/league_stats_rpc.v1.CronWatchService/ForceRefresh',
                request_serializer=league__stats__rpc_dot_v1_dot_cron__watch__pb2.ForceRefreshRequest.SerializeToString,
                response_deserializer=league__stats__rpc_dot_v1_dot_common__pb2.Ack.FromString,
                _registered_method=True)
        self.WatchUpdates = channel.unary_stream(
                '/league_stats_rpc.v1.CronWatchService/WatchUpdates',
                request_serializer=league__stats__rpc_dot_v1_dot_cron__watch__pb2.WatchUpdatesRequest.SerializeToString,
                response_deserializer=league__stats__rpc_dot_v1_dot_cron__watch__pb2.WelcomeBackUpdate.FromString,
                _registered_method=True)


class CronWatchServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterAccount(self, request, context):
        """Called by API-UI when a user submits a new Riot ID to track.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceRefresh(self, request, context):
        """Called by API-UI's "Refresh" button to force an immediate check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchUpdates(self, request, context):
        """Subscribed to by API-UI; pushes a fast update the moment CronWatch
        detects a new game for this account, without waiting on RUNNER.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CronWatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAccount,
                    request_deserializer=league__stats__rpc_dot_v1_dot_cron__watch__pb2.RegisterAccountRequest.FromString,
                    response_serializer=league__stats__rpc_dot_v1_dot_common__pb2.Ack.SerializeToString,
            ),
            'ForceRefresh': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceRefresh,
                    request_deserializer=league__stats__rpc_dot_v1_dot_cron__watch__pb2.ForceRefreshRequest.FromString,
                    response_serializer=league__stats__rpc_dot_v1_dot_common__pb2.Ack.SerializeToString,
            ),
            'WatchUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchUpdates,
                    request_deserializer=league__stats__rpc_dot_v1_dot_cron__watch__pb2.WatchUpdatesRequest.FromString,
                    response_serializer=league__stats__rpc_dot_v1_dot_cron__watch__pb2.WelcomeBackUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'league_stats_rpc.v1.CronWatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('league_stats_rpc.v1.CronWatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CronWatchService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/league_stats_rpc.v1.CronWatchService/RegisterAccount',
            league__stats__rpc_dot_v1_dot_cron__watch__pb2.RegisterAccountRequest.SerializeToString,
            league__stats__rpc_dot_v1_dot_common__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceRefresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/league_stats_rpc.v1.CronWatchService/ForceRefresh',
            league__stats__rpc_dot_v1_dot_cron__watch__pb2.ForceRefreshRequest.SerializeToString,
            league__stats__rpc_dot_v1_dot_common__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/league_stats_rpc.v1.CronWatchService/WatchUpdates',
            league__stats__rpc_dot_v1_dot_cron__watch__pb2.WatchUpdatesRequest.SerializeToString,
            league__stats__rpc_dot_v1_dot_cron__watch__pb2.WelcomeBackUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
