# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: league_stats_rpc/v1/cron_watch.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'league_stats_rpc/v1/cron_watch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from league_stats_rpc.v1 import common_pb2 as league__stats__rpc_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$league_stats_rpc/v1/cron_watch.proto\x12\x13league_stats_rpc.v1\x1a league_stats_rpc/v1/common.proto\"T\n\x16RegisterAccountRequest\x12\r\n\x05puuid\x18\x01 \x01(\t\x12+\n\x06region\x18\x02 \x01(\x0e\x32\x1b.league_stats_rpc.v1.Region\"$\n\x13\x46orceRefreshRequest\x12\r\n\x05puuid\x18\x01 \x01(\t\"$\n\x13WatchUpdatesRequest\x12\r\n\x05puuid\x18\x01 \x01(\t\"n\n\x11WelcomeBackUpdate\x12\r\n\x05puuid\x18\x01 \x01(\t\x12\x14\n\x0cnew_match_id\x18\x02 \x01(\t\x12\x1a\n\x12match_summary_json\x18\x03 \x01(\t\x12\x18\n\x10\x64\x65tected_at_unix\x18\x04 \x01(\x03\x32\xa4\x02\n\x10\x43ronWatchService\x12X\n\x0fRegisterAccount\x12+.league_stats_rpc.v1.RegisterAccountRequest\x1a\x18.league_stats_rpc.v1.Ack\x12R\n\x0c\x46orceRefresh\x12(.league_stats_rpc.v1.ForceRefreshRequest\x1a\x18.league_stats_rpc.v1.Ack\x12\x62\n\x0cWatchUpdates\x12(.league_stats_rpc.v1.WatchUpdatesRequest\x1a&.league_stats_rpc.v1.WelcomeBackUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'league_stats_rpc.v1.cron_watch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERACCOUNTREQUEST']._serialized_start=95
  _globals['_REGISTERACCOUNTREQUEST']._serialized_end=179
  _globals['_FORCEREFRESHREQUEST']._serialized_start=181
  _globals['_FORCEREFRESHREQUEST']._serialized_end=217
  _globals['_WATCHUPDATESREQUEST']._serialized_start=219
  _globals['_WATCHUPDATESREQUEST']._serialized_end=255
  _globals['_WELCOMEBACKUPDATE']._serialized_start=257
  _globals['_WELCOMEBACKUPDATE']._serialized_end=367
  _globals['_CRONWATCHSERVICE']._serialized_start=370
  _globals['_CRONWATCHSERVICE']._serialized_end=662
# @@protoc_insertion_point(module_scope)
