# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: league_stats_rpc/v1/peers.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'league_stats_rpc/v1/peers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fleague_stats_rpc/v1/peers.proto\x12\x13league_stats_rpc.v1\"~\n\x16RequestBaselineRequest\x12\x10\n\x08\x63hampion\x18\x01 \x01(\t\x12\x0c\n\x04lane\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\x15\n\rexclude_puuid\x18\x05 \x01(\t\x12\r\n\x05patch\x18\x06 \x01(\t\"c\n\x17RequestBaselineResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61\x63hed\x18\x02 \x01(\x08\x12\x15\n\rbaseline_json\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"d\n\x13PeekBaselineRequest\x12\x10\n\x08\x63hampion\x18\x01 \x01(\t\x12\x0c\n\x04lane\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\r\n\x05patch\x18\x05 \x01(\t\"T\n\x14PeekBaselineResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x15\n\rbaseline_json\x18\x02 \x01(\t\x12\x16\n\x0estill_refining\x18\x03 \x01(\x08\x32\xe1\x01\n\x0cPeersService\x12l\n\x0fRequestBaseline\x12+.league_stats_rpc.v1.RequestBaselineRequest\x1a,.league_stats_rpc.v1.RequestBaselineResponse\x12\x63\n\x0cPeekBaseline\x12(.league_stats_rpc.v1.PeekBaselineRequest\x1a).league_stats_rpc.v1.PeekBaselineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'league_stats_rpc.v1.peers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTBASELINEREQUEST']._serialized_start=56
  _globals['_REQUESTBASELINEREQUEST']._serialized_end=182
  _globals['_REQUESTBASELINERESPONSE']._serialized_start=184
  _globals['_REQUESTBASELINERESPONSE']._serialized_end=283
  _globals['_PEEKBASELINEREQUEST']._serialized_start=285
  _globals['_PEEKBASELINEREQUEST']._serialized_end=385
  _globals['_PEEKBASELINERESPONSE']._serialized_start=387
  _globals['_PEEKBASELINERESPONSE']._serialized_end=471
  _globals['_PEERSSERVICE']._serialized_start=474
  _globals['_PEERSSERVICE']._serialized_end=699
# @@protoc_insertion_point(module_scope)
