# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from league_stats_rpc.v1 import peers_pb2 as league__stats__rpc_dot_v1_dot_peers__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in league_stats_rpc/v1/peers_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeersServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestBaseline = channel.unary_unary(
                '/league_stats_rpc.v1.PeersService/RequestBaseline',
                request_serializer=league__stats__rpc_dot_v1_dot_peers__pb2.RequestBaselineRequest.SerializeToString,
                response_deserializer=league__stats__rpc_dot_v1_dot_peers__pb2.RequestBaselineResponse.FromString,
                _registered_method=True)
        self.PeekBaseline = channel.unary_unary(
                '/league_stats_rpc.v1.PeersService/PeekBaseline',
                request_serializer=league__stats__rpc_dot_v1_dot_peers__pb2.PeekBaselineRequest.SerializeToString,
                response_deserializer=league__stats__rpc_dot_v1_dot_peers__pb2.PeekBaselineResponse.FromString,
                _registered_method=True)


class PeersServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RequestBaseline(self, request, context):
        """Called by RUNNER when it needs a champion+lane+rank peer baseline.
        If not cached, PEERS enqueues its own fetch and calls back into
        RunnerService.NotifyPeerBaselineReady when done.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeekBaseline(self, request, context):
        """Read-only: returns whatever is currently cached for this key, or
        found=false. Never enqueues a SamplingTask -- callers that want PEERS
        to actually go fetch data must use RequestBaseline instead. Meant for
        a cheap "has this improved since I last saved it" check on report
        read, not for resolving a baseline from scratch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestBaseline': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestBaseline,
                    request_deserializer=league__stats__rpc_dot_v1_dot_peers__pb2.RequestBaselineRequest.FromString,
                    response_serializer=league__stats__rpc_dot_v1_dot_peers__pb2.RequestBaselineResponse.SerializeToString,
            ),
            'PeekBaseline': grpc.unary_unary_rpc_method_handler(
                    servicer.PeekBaseline,
                    request_deserializer=league__stats__rpc_dot_v1_dot_peers__pb2.PeekBaselineRequest.FromString,
                    response_serializer=league__stats__rpc_dot_v1_dot_peers__pb2.PeekBaselineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'league_stats_rpc.v1.PeersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('league_stats_rpc.v1.PeersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeersService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestBaseline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/league_stats_rpc.v1.PeersService/RequestBaseline',
            league__stats__rpc_dot_v1_dot_peers__pb2.RequestBaselineRequest.SerializeToString,
            league__stats__rpc_dot_v1_dot_peers__pb2.RequestBaselineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PeekBaseline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/league_stats_rpc.v1.PeersService/PeekBaseline',
            league__stats__rpc_dot_v1_dot_peers__pb2.PeekBaselineRequest.SerializeToString,
            league__stats__rpc_dot_v1_dot_peers__pb2.PeekBaselineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
