# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from league_stats_rpc.v1 import common_pb2 as league__stats__rpc_dot_v1_dot_common__pb2
from league_stats_rpc.v1 import runner_pb2 as league__stats__rpc_dot_v1_dot_runner__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in league_stats_rpc/v1/runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunnerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueJob = channel.unary_unary(
                '/league_stats_rpc.v1.RunnerService/EnqueueJob',
                request_serializer=league__stats__rpc_dot_v1_dot_runner__pb2.EnqueueJobRequest.SerializeToString,
                response_deserializer=league__stats__rpc_dot_v1_dot_runner__pb2.EnqueueJobResponse.FromString,
                _registered_method=True)
        self.StreamJobProgress = channel.unary_stream(
                '/league_stats_rpc.v1.RunnerService/StreamJobProgress',
                request_serializer=league__stats__rpc_dot_v1_dot_runner__pb2.StreamJobProgressRequest.SerializeToString,
                response_deserializer=league__stats__rpc_dot_v1_dot_runner__pb2.StageResult.FromString,
                _registered_method=True)
        self.NotifyPeerBaselineReady = channel.unary_unary(
                '/league_stats_rpc.v1.RunnerService/NotifyPeerBaselineReady',
                request_serializer=league__stats__rpc_dot_v1_dot_runner__pb2.PeerBaselineReadyRequest.SerializeToString,
                response_deserializer=league__stats__rpc_dot_v1_dot_common__pb2.Ack.FromString,
                _registered_method=True)


class RunnerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def EnqueueJob(self, request, context):
        """Called by CronWatch (new match detected) or API-UI (on-demand action).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobProgress(self, request, context):
        """Subscribed to by API-UI; pushes each pipeline stage's result as soon
        as it completes (summary, performance, deep-dive, champion) instead
        of waiting for the whole pipeline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyPeerBaselineReady(self, request, context):
        """Called by PEERS when a previously-requested baseline is ready.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueJob': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueJob,
                    request_deserializer=league__stats__rpc_dot_v1_dot_runner__pb2.EnqueueJobRequest.FromString,
                    response_serializer=league__stats__rpc_dot_v1_dot_runner__pb2.EnqueueJobResponse.SerializeToString,
            ),
            'StreamJobProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobProgress,
                    request_deserializer=league__stats__rpc_dot_v1_dot_runner__pb2.StreamJobProgressRequest.FromString,
                    response_serializer=league__stats__rpc_dot_v1_dot_runner__pb2.StageResult.SerializeToString,
            ),
            'NotifyPeerBaselineReady': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyPeerBaselineReady,
                    request_deserializer=league__stats__rpc_dot_v1_dot_runner__pb2.PeerBaselineReadyRequest.FromString,
                    response_serializer=league__stats__rpc_dot_v1_dot_common__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'league_stats_rpc.v1.RunnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('league_stats_rpc.v1.RunnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunnerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnqueueJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/league_stats_rpc.v1.RunnerService/EnqueueJob',
            league__stats__rpc_dot_v1_dot_runner__pb2.EnqueueJobRequest.SerializeToString,
            league__stats__rpc_dot_v1_dot_runner__pb2.EnqueueJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/league_stats_rpc.v1.RunnerService/StreamJobProgress',
            league__stats__rpc_dot_v1_dot_runner__pb2.StreamJobProgressRequest.SerializeToString,
            league__stats__rpc_dot_v1_dot_runner__pb2.StageResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyPeerBaselineReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/league_stats_rpc.v1.RunnerService/NotifyPeerBaselineReady',
            league__stats__rpc_dot_v1_dot_runner__pb2.PeerBaselineReadyRequest.SerializeToString,
            league__stats__rpc_dot_v1_dot_common__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
