# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: league_stats_rpc/v1/runner.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'league_stats_rpc/v1/runner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from league_stats_rpc.v1 import common_pb2 as league__stats__rpc_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n league_stats_rpc/v1/runner.proto\x12\x13league_stats_rpc.v1\x1a league_stats_rpc/v1/common.proto\"q\n\x11\x45nqueueJobRequest\x12\r\n\x05puuid\x18\x01 \x01(\t\x12+\n\x06region\x18\x02 \x01(\x0e\x32\x1b.league_stats_rpc.v1.Region\x12\x10\n\x08match_id\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\"$\n\x12\x45nqueueJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"*\n\x18StreamJobProgressRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"y\n\x0bStageResult\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12)\n\x05stage\x18\x02 \x01(\x0e\x32\x1a.league_stats_rpc.v1.Stage\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\x12\x19\n\x11\x63ompleted_at_unix\x18\x04 \x01(\x03\"s\n\x18PeerBaselineReadyRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08\x63hampion\x18\x02 \x01(\t\x12\x0c\n\x04lane\x18\x03 \x01(\t\x12\x0c\n\x04rank\x18\x04 \x01(\t\x12\x15\n\rbaseline_json\x18\x05 \x01(\t2\xba\x02\n\rRunnerService\x12]\n\nEnqueueJob\x12&.league_stats_rpc.v1.EnqueueJobRequest\x1a\'.league_stats_rpc.v1.EnqueueJobResponse\x12\x66\n\x11StreamJobProgress\x12-.league_stats_rpc.v1.StreamJobProgressRequest\x1a .league_stats_rpc.v1.StageResult0\x01\x12\x62\n\x17NotifyPeerBaselineReady\x12-.league_stats_rpc.v1.PeerBaselineReadyRequest\x1a\x18.league_stats_rpc.v1.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'league_stats_rpc.v1.runner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENQUEUEJOBREQUEST']._serialized_start=91
  _globals['_ENQUEUEJOBREQUEST']._serialized_end=204
  _globals['_ENQUEUEJOBRESPONSE']._serialized_start=206
  _globals['_ENQUEUEJOBRESPONSE']._serialized_end=242
  _globals['_STREAMJOBPROGRESSREQUEST']._serialized_start=244
  _globals['_STREAMJOBPROGRESSREQUEST']._serialized_end=286
  _globals['_STAGERESULT']._serialized_start=288
  _globals['_STAGERESULT']._serialized_end=409
  _globals['_PEERBASELINEREADYREQUEST']._serialized_start=411
  _globals['_PEERBASELINEREADYREQUEST']._serialized_end=526
  _globals['_RUNNERSERVICE']._serialized_start=529
  _globals['_RUNNERSERVICE']._serialized_end=843
# @@protoc_insertion_point(module_scope)
